Revert "feat/knowledge base (#658)" (#722)
This reverts commit 0208b362dfa2b3288cd267f54378a16925153a10.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,24 +1,24 @@
-# #!/bin/sh
-# set -u
+#!/bin/sh
+set -u
 
-# # Function to check formatting and then format if necessary
-# check_and_format() {
-#     # Temporarily disable exit on error
-#     set +e
-#     cd server
-#     bunx @biomejs/biome check ../ --formatter-enabled=true --linter-enabled=false --vcs-use-ignore-file=true --organize-imports-enabled=false
-#     CHECK_STATUS=$?
-#     # set -e
-#     if [ $CHECK_STATUS -ne 0 ]; then
-#         echo "Formatting issues detected. Running formatter..."
+# Function to check formatting and then format if necessary
+check_and_format() {
+    # Temporarily disable exit on error
+    set +e
+    cd server
+    bunx @biomejs/biome check ../ --formatter-enabled=true --linter-enabled=false --vcs-use-ignore-file=true --organize-imports-enabled=false
+    CHECK_STATUS=$?
+    # set -e
+    if [ $CHECK_STATUS -ne 0 ]; then
+        echo "Formatting issues detected. Running formatter..."
 
-#         # Format all applicable files, not just staged ones
-#         bun run format
+        # Format all applicable files, not just staged ones
+        bun run format
         
-#         echo "Files have been formatted. Please add them to staging and commit again."
-#         exit 1
-#     fi
-# }
+        echo "Files have been formatted. Please add them to staging and commit again."
+        exit 1
+    fi
+}
 
-# # Run the check and format function
-# check_and_format
+# Run the check and format function
+check_and_format
